version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "09:00"
    timezone: Asia/Chongqing
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rollup
    versions:
    - 2.38.2
- package-ecosystem: npm
  directory: "/packages/class-names"
  schedule:
    interval: monthly
    time: "09:00"
    timezone: Asia/Chongqing
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/packages/text-clamp"
  schedule:
    interval: monthly
    time: "09:00"
    timezone: Asia/Chongqing
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/packages/uuidv4"
  schedule:
    interval: monthly
    time: "09:00"
    timezone: Asia/Chongqing
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: typescript
    versions:
    - 4.2.2
- package-ecosystem: npm
  directory: "/packages/webp-supported"
  schedule:
    interval: monthly
    time: "09:00"
    timezone: Asia/Chongqing
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: typescript
    versions:
    - 4.2.2
- package-ecosystem: npm
  directory: "/packages/throttle-debounce"
  schedule:
    interval: monthly
    time: "09:00"
    timezone: Asia/Chongqing
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: typescript
    versions:
    - 4.2.2
- package-ecosystem: npm
  directory: "/packages/luci-types"
  schedule:
    interval: monthly
    time: "09:00"
    timezone: Asia/Chongqing
  open-pull-requests-limit: 10
