version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "monthly"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"

  - package_manager: "javascript"
    directory: "/packages/class-names/"
    update_schedule: "monthly"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"

  - package_manager: "javascript"
    directory: "/packages/luci-types/"
    update_schedule: "monthly"

  - package_manager: "javascript"
    directory: "/packages/text-clamp/"
    update_schedule: "monthly"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"

  - package_manager: "javascript"
    directory: "/packages/throttle-debounce/"
    update_schedule: "monthly"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"

  - package_manager: "javascript"
    directory: "/packages/uuidv4/"
    update_schedule: "monthly"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"

  - package_manager: "javascript"
    directory: "/packages/webp-supported/"
    update_schedule: "monthly"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
