name: Node.js Package CI

on: 
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install base packages
        run: yarn install

      - id: getpackage
        name: Get changed packages
        run: |
          changed_files="$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})"

          echo "Changed files: $changed_files"

          changed_packages="$(echo "$changed_files" | sed -n 's|^packages/\([^/]\{1,\}\)/.*$|\1|p' | sort -u | xargs)"

          if [ -n "$changed_packages" ] ; then
            echo "Packges changed: $changed_packages"
          else
            echo "No packages changed."
          fi

          echo "::set-output name=packages::$changed_packages"

      - name: Build test
        if: steps.getpackage.outputs.packages != ''
        run: |
          for pkg in ${{ steps.getpackage.outputs.packages }} ; do
            echo "Testing build for $pkg..."

            cd "${{ github.workspace }}/packages/$pkg"

            yarn install
            yarn build

            echo "$pkg build success."
          done

          cd "${{ github.workspace }}"
