name: Node.js Package CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install base packages
        run: yarn install
      - name: Build test
        run: |
          changed_packages=$(
            git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | \
            sed -n "s|^packages/\([^/]*\)/.*$|\1|p" | sort -u
          )

          if [ -n "$changed_packages" ] ; then
            echo "Changed packages: $changed_packages"
          else
            echo "No packages changed."
            exit 0
          fi

          for pkg in $changed_packages ; do
            echo "Testing build for $pkg..."
            cd "${{ github.workspace }}/packages/$pkg"
            yarn install
            yarn build
            echo "$pkg build success."
          done
          cd "${{ github.workspace }}"
