name: Node.js Package CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install base packages
        run: yarn install

      - id: getfile
        name: Get changed files
        run: |
          echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})"

      - id: getpackage
        name: Get changed packages
        run: |
          changed_packages="$(echo "${{ steps.getfile.outputs.files }}" | sed -n 's|^packages/\([^/]*\)/.*$|\1|p' | sort -u)"

          echo "::set-output name=packages::$changed_packages"

          if [ -n "$changed_packages" ] ; then
            echo "Packges changed: $changed_packages"
          else
            echo "No packages changed."
          fi

      - name: Build test
        if: steps.getpackage.outputs.packages != ''
        run: |
          for pkg in ${{ steps.getpackage.outputs.packages }} ; do
            echo "Testing build for $pkg..."

            cd "${{ github.workspace }}/packages/$pkg"

            yarn install
            yarn build

            echo "$pkg build success."
          done

          cd "${{ github.workspace }}"
