name: Node.js Package CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install base packages
        run: yarn install

      - id: get_changed_packages
        name: Get changed packages
        run: |
          changed_files="$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})"

          echo "Changed files: $changed_files"

          changed_packages="$(echo "$changed_files" | sed -n 's|^packages/\([^/]*\)/.*$|\1|p' | sort -u)"

          echo "::set-output name=all::$changed_packages"

          if [ -n "$changed_packages" ] ; then
            echo "No packages changed."
          else
            echo "Packges changed: $changed_packages"
          fi

      - name: Build test
        if: steps.get_changed_packages.outputs.value != ''
        run: |
          for pkg in ${{ steps.get_changed_packages.outputs.value }} ; do
            echo "Testing build for $pkg..."

            cd "${{ github.workspace }}/packages/$pkg"

            yarn install
            yarn build

            echo "$pkg build success."
          done

          cd "${{ github.workspace }}"
